# Generated by Django 3.1.3 on 2020-12-02 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autor', to='libros.persona'),
        ),
    ]
