# Generated by Django 3.1.3 on 2020-12-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_autor_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='persona',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
